#!/bin/bash
# updates 0install stream xml for new release 

# expected variables:
# SERIES
# VERSION
# FILE
# PACKAGE
# OSTAG_GENERIC

set -x

# transform version for 0install
ZEROVERSION=$(echo ${VERSION} | sed -e "s,_,-,g" -e "s,-alpha,-pre0.," -e "s,-beta,-pre1.," )
# and launchpad
LPVERSION=$(echo ${VERSION} | sed -e "s,_,-,g" )

WINFILE=$(echo ${FILE} | sed -e "s,\.${OSTAG_GENERIC},.win32," -e "s,\.bin\.tar\.bz2,.zip,")

# construct uri
URI=http://launchpad.net/armagetronad/${SERIES}/${LPVERSION}/+download/$(basename ${FILE})
WINURI=http://launchpad.net/armagetronad/${SERIES}/${LPVERSION}/+download/$(basename ${WINFILE})

# determine xml to modify
XML=0install/${PACKAGE}

# exception: plain 0.2.8 builds always go to the beta feed first
if test ${SERIES} == 0.2.8; then
    echo ${PACKAGE} | grep beta || XML=$(echo ${XML} | sed -e 's,armagetronad,armagetronad-beta,')
fi

OS=Linux
CPU=$(echo ${OSTAG_GENERIC} | sed -e "s,-.*,,")
ARCH=${OS}-${CPU}

# add the release
if test -r ${FILE} && ! grep -q version=\"${ZEROVERSION}\" ${XML}-${ARCH}.xml; then
  0launch -c 'http://0install.net/2006/interfaces/0publish' \
  ${XML}-${ARCH}.xml \
 --add-version ${ZEROVERSION} \
 --archive-url=${URI} \
 --archive-file=${FILE} \
 --set-released=today \
 --set-main=AppRun
fi

if test -r ${WINFILE} && ! grep -q version=\"${ZEROVERSION}\" ${XML}-Windows.xml; then
  0launch -c 'http://0install.net/2006/interfaces/0publish' \
  ${XML}-Windows.xml \
 --add-version ${ZEROVERSION} \
 --archive-url=${WINURI} \
 --archive-file=${WINFILE} \
 --archive-extract="" \
 --set-released=today
fi

