.\"                                      Hey, EMACS: -*- nroff -*-
.TH ARMAGETRONAD 6 "January 30, 2005"
.SH NAME
armagetronad \- A 3D Tron-like high speed game
.SH SYNOPSIS
.B armagetronad
.SH DESCRIPTION
The rules are simple: you ride a lightcycle (a kind of motorbike that
can only turn 90 degrees at a time, leaves a wall behind and cannot be
stopped).  Avoid running into a wall.  Make your opponent run into a
wall.  (Just in case you do not know: this idea is stolen from the
Disney movie "Tron" from 1982 (did they steal the idea from someone
else? I don't know).)
.PP
One thing is different than in other Tron clones: You can accelerate.
Oh, not by pressing an acceleration button, that would not be new.  You
accelerate by driving close to walls (Only player walls count, the rim
has no such effect.)  That allows some interesting tactics (of course,
the AI players are not smart enough for that).  Every time you make a
turn, you lose 5% of your speed, so don't be to nervous; speed is your
only resource against other players!
.PP
First thing you shold do is go into the "Player Menu", set your name and
your keyboard and mouse configuration.  Then, go into the "Game Menu" and
start a single player game against one AI opponent (the game mode does
not really matter here).  Then, get some friends together and try the
multiplayer modes!
.PP
\fBSHIFT-ESC\fP is the "boss key" and quits Armagetron Advanced as fast as
possible.
.SH SEE ALSO
Armagetron Advanced is documented fully by the provided HTML docs, found under
/usr/share/doc/armagetronad/ or the armagetronad website,
\fIhttp://armagetronad.sourceforge.net/\fP.
.SH AUTHOR
Armagetron Advanced is based on Armagetron (written by Manuel Moos)
Armagetron Advanced is written by AA-DevTeam (see AUTHORS)
.P
This manual was updated for Armagetron Advanced. The Armagetron manual page
was adapted from the original HTML version by Marcelo
E. Magallon <mmagallo@debian.org>, for the Debian GNU/Linux system (but
may be used by others).
