#!/bin/bash
# handles dumped windows dist file

set -x

cd ${RCDIR}
test -d windist && mv windist windist.back
cp -ax Upload/dist windist

pushd Upload/dist
# build nsis installers
for f in arma*.nsi; do 
  if test -r $f; then
    wine C:/Program\ Files/NSIS/makensis.exe $f || exit 1
  fi
done
mv *.win32.exe ../
rm -f *.nsi

# zip up 
#rm -f *_dedicated.exe
rm -f *_master.exe
rm -f *.a *.def banner.bmp var
mkdir -p ../ZeroInstall
zip -r ../../${PACKAGE}-libs-${VERSION}.win32.zip *.dll || exit 1
rm -f *.dll
rm -rf textures models sound music
zip -r ../ZeroInstall/${PACKAGE}-${VERSION}.win32.zip * -x *_dedicated.exe || exit 1
zip -r ../ZeroInstall/${PACKAGE}-dedicated-${VERSION}.win32.zip * -x armagetronad.exe ArmagetronAd.exe || exit 1
popd

# discard garbage
rm -rf Upload/dist

