#!/bin/sh
# packs windows sources

# set -x

WINDIR=$1
SRCDIR=$2
BUILDDIR=$3
DOCDIR=$4
VERSION=$5

# prepare windows sources
rm -rf $WINDIR
cp -ax $SRCDIR $WINDIR || exit 1
rm -rf $WINDIR/src/doc
rm -rf $WINDIR/doc
cp -r $DOCDIR $WINDIR/src/doc || exit 1
cp -r $BUILDDIR/language/languages.txt $WINDIR/language || exit 1
cp -r $BUILDDIR/config/aiplayers.cfg $WINDIR/config || exit 1

# rename text files
for f in $WINDIR/INSTALL $WINDIR/COPYING $WINDIR/AUTHORS $WINDIR/NEWS $WINDIR/ChangeLog `find $WINDIR -name "*README*"`; do
    mv $f $f.txt || exit 1
done

# transcribe nsi scripts
for f in ${WINDIR}/win32/*.nsi; do
	#echo Adapting installer script $f...
    mv $f $f.in
	sed < $f.in > $f \
        -e "s,define PRODUCT_VERSION.*$,define PRODUCT_VERSION \"${VERSION}\","\
        -e "s,define PRODUCT_BASENAME.*$,define PRODUCT_BASENAME \"${PROGNAME}\"," \

    rm $f.in
done

# copy version file
cp ${WINDIR}/src/tFakeVersion.h ${WINDIR}/src/tTrueVersion.h

# append windows specific stuff
WINVERSION=`echo $VERSION | sed -e 's/\./,/g' -e 's/_alpha/,/' -e 's/_beta/,/' -e 's/_rc/,/'`
MINVERSION=`echo $VERSION | sed -e 's/^.*_/_/'`
echo "#define MINOR_VERSION ${MINVERSION}"      >> ${WINDIR}/src/tTrueVersion.h
echo "#define MAJOR_VERSION ${WINVERSION}"      >> ${WINDIR}/src/tTrueVersion.h

# transcode to windows CR/LF line mode
for suffix in bat nsi nsi.m4 cfg txt dsp dsw h cpp dtd xml; do
	find $WINDIR -name "*.$suffix" -exec recode latin1..latin1/CR-LF \{\} \;
done

rm -rf $WINDIR/config.* $WINDIR/configure* $WINDIR/*.m4 $WINDIR/*.kde* 
rm -rf $WINDIR/*.sh $WINDIR/batch $WINDIR/missing $WINDIR/install-sh $WINDIR/textures/KGN*
find $WINDIR -name "*.in" -exec rm \{\} \;
find $WINDIR -name "*.am" -exec rm \{\} \;
find $WINDIR -name "Makefile*" -exec rm \{\} \;
find $WINDIR -name "*.ghost" -exec rm \{\} \;
find $WINDIR -depth -name "CVS" -exec rm -rf \{\} \;
find $WINDIR -depth -name "*~" -exec rm -rf \{\} \;
