#!/bin/bash

cd $(dirname "${0}")
EXEC=$(grep -m 1 -r Exec= ./*.desktop | cut -d "=" -f 2 | cut -d % -f 1)
# append library path so system libraries are found first (if we put our libs into /usr/lib),
# same for executables.
LD_LIBRARY_PATH="./usr/local/lib:${LD_LIBRARY_PATH}:./usr/lib" PATH="./usr/local/bin:${PATH}:./usr/bin" exec $EXEC $@
#LD_LIBRARY_PATH="./usr/local/lib:./usr/lib:${LD_LIBRARY_PATH}" PATH="${PATH}:./usr/local/bin:./usr/bin" exec $EXEC $@
